# 0. Setup

In [1]:
import pandas as pd
import requests
import json
import datetime as dt
import plotly.express as px
import plotly.graph_objects as go
import os
import yfinance as yf

# 1. API Request

In [2]:
url = 'https://api.hkma.gov.hk/public/market-data-and-statistics/daily-monetary-statistics/daily-figures-interbank-liquidity?offset=0&pagesize=999&sortby=end_of_date&sortorder=desc'
response = requests.get(url).text
response = json.loads(response)
df = pd.DataFrame(response['result']['records'])
df['end_of_date'] = pd.to_datetime(df['end_of_date'])

In [3]:
df

,end_of_date,cu_weakside,cu_strongside,disc_win_base_rate,hibor_overnight,hibor_fixing_1m,twi,opening_balance,closing_balance,market_activities,...,forex_trans_t4,other_market_activities_t4,reversal_of_discount_window_t4,interest_payment_issuance_efbn_t4,forecast_aggregate_bal_t4,forex_trans_u,other_market_activities_u,reversal_of_discount_window_u,interest_payment_issuance_efbn_u,forecast_aggregate_bal_u
0,2025-08-28,7.85,7.75,4.75,3.83,3.30649,103.6,54056,54061,+0,...,None,None,None,None,NaN,+0,+0,-0,-750,53311
1,2025-08-27,7.85,7.75,4.75,3.11,3.23310,104.0,53948,54056,+0,...,+0,+0,-0,+0,54061.0,+0,+0,-0,-750,53311
2,2025-08-26,7.85,7.75,4.75,2.59,2.81464,103.7,53944,53948,+0,...,None,None,None,None,NaN,+0,+0,-0,-750,53311
3,2025-08-25,7.85,7.75,4.75,2.54,2.72720,103.4,53877,53944,+0,...,None,None,None,None,NaN,+0,+0,-0,-653,53311
4,2025-08-22,7.85,7.75,4.75,2.61,2.77060,103.8,53852,53877,+0,...,None,None,None,None,NaN,+0,+0,-0,-648,53311
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,2021-08-18,7.85,7.75,0.50,0.03,0.07804,101.6,457456,457457,0,...,None,None,None,None,NaN,0,0,0,-38,457454
995,2021-08-17,7.85,7.75,0.50,0.01,0.06750,101.6,457456,457456,0,...,None,None,None,None,NaN,0,0,0,-23,457454
996,2021-08-16,7.85,7.75,0.50,0.01,0.06411,101.6,457456,457456,0,...,None,None,None,None,NaN,0,0,0,-3,457454
997,2021-08-13,7.85,7.75,0.50,0.01,0.06554,101.7,457456,457456,0,...,None,None,None,None,NaN,0,0,0,-3,457454
998,2021-08-12,7.85,7.75,0.50,0.01,0.06589,101.7,457456,457456,0,...,None,None,None,None,NaN,0,0,0,-2,457454

In [4]:
# HKAB API URLs for yield data
def get_hibor(startDate, endDate)->pd.DataFrame:
    selected_keys = ['Overnight', '1 Week', '2 Weeks', '1 Month', '2 Months', '3 Months', '6 Months', '12 Months']
    hibor_df = pd.DataFrame(columns=selected_keys)
    for date in pd.date_range(startDate, endDate):
        # print(date)
        if date.dayofweek <5:
            year = date.year
            month = date.month
            day = date.day
            hibor_url = f"https://www.hkab.org.hk/api/hibor?year={year}&month={month}&day={day}"
            hibor_response = requests.get(hibor_url).json()
            if hibor_response['isHoliday']==False:
                temp_df = pd.DataFrame(hibor_response, index=[date], columns=selected_keys)
                hibor_df = pd.concat([hibor_df, temp_df], ignore_index=False)
    hibor_df=hibor_df.dropna().sort_index(ascending=False).reset_index(drop=False).rename(columns={'index':'date'})
    return hibor_df

In [5]:
endDate = pd.Timestamp.now(tz='Asia/Hong_Kong').strftime('%Y-%m-%d')
startDate =(pd.Timestamp.now(tz='Asia/Hong_Kong') - pd.Timedelta(days=365)).strftime('%Y-%m-%d')
hibor_df = get_hibor(startDate, endDate)
hibor_df

/var/folders/h_/dmgktz0n27g262j_0g_v4qvm0000gn/T/ipykernel_5541/2616980000.py:15: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  hibor_df = pd.concat([hibor_df, temp_df], ignore_index=False)
/var/folders/h_/dmgktz0n27g262j_0g_v4qvm0000gn/T/ipykernel_5541/2616980000.py:15: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  hibor_df = pd.concat([hibor_df, temp_df], ignore_index=False)
/var/folders/h_/dmgktz0n27g262j_0g_v4qvm0000gn/T/ipykernel_5541/2616980000.py:15: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  hibor_df = pd.concat([hibor_df, temp_df], ignore_index=False)
/var/folders/h_/dmgktz0n27g262j_0g_v4qvm0000gn/T/ipykernel_5541/2616980000.py:15: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  hibor_df = pd.concat([hibor_df, temp_df], ignore_index=False)

,date,Overnight,1 Week,2 Weeks,1 Month,2 Months,3 Months,6 Months,12 Months
0,2025-08-29,3.98226,3.70548,3.64774,3.30649,3.30649,3.30720,3.26524,3.30363
1,2025-08-28,3.98226,3.70548,3.64774,3.30649,3.30649,3.30720,3.26524,3.30363
2,2025-08-27,3.12357,3.16429,3.16643,3.23310,3.23381,3.27310,3.23036,3.23393
3,2025-08-26,2.73750,2.90786,2.86417,2.81464,2.91393,2.91393,2.98691,3.09863
4,2025-08-25,2.66345,2.80964,2.78262,2.72720,2.75286,2.78952,2.97905,3.08161
...,...,...,...,...,...,...,...,...,...
240,2024-09-04,3.42357,3.54524,3.62369,3.88857,4.07452,4.15637,4.20000,4.24625
241,2024-09-03,3.37774,3.59286,3.69000,3.89929,4.08244,4.17083,4.20000,4.24625
242,2024-09-02,4.44452,3.83060,3.85976,3.93905,4.11280,4.20000,4.22750,4.26619
243,2024-08-30,3.41952,3.92179,3.90786,3.93095,4.11351,4.20000,4.24554,4.27589
244,2024-08-29,3.21631,3.83476,3.83500,3.92661,4.10619,4.19363,4.23364,4.27994

# 2.0 HIBOR & Liquidity

## 2.1 HIBOR (Overnight & 1-Month)

In [6]:
hibor_df = hibor_df.head(251)

In [58]:
hibor_fig = px.line(hibor_df,
             x='date', y=['Overnight', '1 Week', '1 Month', '3 Months', '6 Months', '12 Months'],
             title='HIBOR Rates',
             labels={'end_of_date': 'Date', 'value': 'HIBOR Rate (%)'},
             )

last_date = hibor_df['date'].iloc[0].strftime('%Y-%m-%d')
last_overnight = round(hibor_df['Overnight'].iloc[0],2)
last_1m = round(hibor_df['1 Month'].iloc[0], 2)
last_3m = round(hibor_df['3 Months'].iloc[0], 2)
last_6m = round(hibor_df['6 Months'].iloc[0], 2)
last_12m = round(hibor_df['12 Months'].iloc[0], 2)

hibor_fig.add_annotation(
    text=f"Date: {last_date}<br>Overnight: {last_overnight}%<br>1M: {last_1m}%<br>3M: {last_3m}%<br>6M: {last_6m}%<br>12M: {last_12m}%",
    xref="paper", yref="paper",
    x=1, y=1.2,  
    showarrow=False,
    bgcolor="rgba(1, 108, 2, 1)",
    borderwidth=2,
    font=dict(size=12, color="white"),
    align='right',
)

hibor_fig.update_layout(
    xaxis_rangeslider_visible=True,
)

hibor_fig.update_xaxes(
    rangeslider_visible=True,
    rangeselector=dict(
        buttons=list([
            dict(count=1, label="1m", step="month", stepmode="backward"),
            dict(count=6, label="6m", step="month", stepmode="backward"),
            dict(count=1, label="YTD", step="year", stepmode="todate"),
            dict(count=1, label="1y", step="year", stepmode="backward"),
            dict(step="all")
        ])
    )
)

hibor_fig.show()

## 2.2 Aggregate Balance Open & Close

In [8]:
aggreBal_df = df[['end_of_date', 'opening_balance', 'closing_balance']].head(251)
aggreBal_df['day_change'] = aggreBal_df['closing_balance'] - aggreBal_df['opening_balance']
aggreBal_df['high'] = aggreBal_df[['opening_balance', 'closing_balance']].max(axis=1)
aggreBal_df['low'] = aggreBal_df[['opening_balance', 'closing_balance']].min(axis=1)
aggreBal_df

    end_of_date  opening_balance  closing_balance  day_change   high    low
0    2025-08-28            54056            54061           5  54061  54056
1    2025-08-27            53948            54056         108  54056  53948
2    2025-08-26            53944            53948           4  53948  53944
3    2025-08-25            53877            53944          67  53944  53877
4    2025-08-22            53852            53877          25  53877  53852
..          ...              ...              ...         ...    ...    ...
246  2024-08-28            44888            44891           3  44891  44888
247  2024-08-27            44871            44888          17  44888  44871
248  2024-08-26            44829            44871          42  44871  44829
249  2024-08-23            44826            44829           3  44829  44826
250  2024-08-22            44747            44826          79  44826  44747

[251 rows x 6 columns]

In [59]:
aggreBal_fig = go.Figure(data=[go.Candlestick(
    x=aggreBal_df['end_of_date'],
    open=aggreBal_df['opening_balance'],
    high=aggreBal_df['high'],
    low=aggreBal_df['low'],
    close=aggreBal_df['closing_balance'],
    name='Aggregate Balance',
    showlegend=True,
)])

last_date = aggreBal_df['end_of_date'].iloc[0]
last_open = aggreBal_df['opening_balance'].iloc[0]
last_close = aggreBal_df['closing_balance'].iloc[0]
last_day_change = aggreBal_df['day_change'].iloc[0]

aggreBal_fig.add_annotation(
    text=f"Date: {last_date.strftime('%Y-%m-%d')}<br>Open: {last_open}<br>Close: {last_close}<br>Change: {last_day_change}",
    xref="paper", yref="paper",
    x=1, y=1.2,
    showarrow=False,
    bgcolor="rgba(0, 78, 123, 1)",
    borderwidth=2,
    font=dict(size=12, color="white")
)

aggreBal_fig.update_layout(
    xaxis_rangeslider_visible=True,
    title="Hong Kong Aggregate Balance (Candlestick)",
    xaxis_title="Date",
    yaxis_title="Balance (HKD Million)",
)

aggreBal_fig.update_xaxes(
    rangeslider_visible=True,
    rangeselector=dict(
        buttons=list([
            dict(count=1, label="1m", step="month", stepmode="backward"),
            dict(count=6, label="6m", step="month", stepmode="backward"),
            dict(count=1, label="YTD", step="year", stepmode="todate"),
            dict(count=1, label="1y", step="year", stepmode="backward"),
            dict(step="all")
        ])
    )
)

aggreBal_fig.show()

# 3.0 FX

# 3.1 Convertibility Undertaking (CU)

In [10]:
usdhkd = yf.Ticker("HKD=X")
usdhkd_df = usdhkd.history(period ='max').reset_index()
usdhkd_df['Date'] = pd.to_datetime(usdhkd_df['Date'], format='%Y-%m-%d')
usdhkd_df = usdhkd_df[['Date', 'Close']]
usdhkd_df = usdhkd_df.rename(columns={'Date': 'end_of_date', 'Close': 'usdhkd_close'})
usdhkd_df['end_of_date'] = pd.to_datetime(usdhkd_df['end_of_date'])
usdhkd_df.set_index('end_of_date', inplace=True)
usdhkd_df.index = usdhkd_df.index.tz_localize(None)

In [11]:
cu_df = df[['end_of_date', 'cu_weakside', "cu_strongside"]].head(251)
cu_df['end_of_date'] = pd.to_datetime(cu_df['end_of_date'])
cu_df = cu_df.set_index('end_of_date').join(usdhkd_df, on='end_of_date', how='left')

In [12]:
cu_df = cu_df.reset_index()
cu_df.sort_values(by='end_of_date', ascending=False, inplace=True)
cu_df

    end_of_date  cu_weakside  cu_strongside  usdhkd_close
0    2025-08-28         7.85           7.75       7.79394
1    2025-08-27         7.85           7.75       7.79358
2    2025-08-26         7.85           7.75       7.81270
3    2025-08-25         7.85           7.75       7.81560
4    2025-08-22         7.85           7.75       7.81390
..          ...          ...            ...           ...
246  2024-08-28         7.85           7.75       7.80180
247  2024-08-27         7.85           7.75       7.79680
248  2024-08-26         7.85           7.75       7.79690
249  2024-08-23         7.85           7.75       7.79680
250  2024-08-22         7.85           7.75       7.79264

[251 rows x 4 columns]

In [60]:
cu_fig = px.line(cu_df,
             x='end_of_date', y=['usdhkd_close', 'cu_weakside', 'cu_strongside'],
             title='USD/HKD and Currency Pegs',
             labels={'end_of_date': 'Date', 'value': 'Value (HKD)'},
             )


last_date = cu_df['end_of_date'].iloc[0]
last_usdhkd_close = round(cu_df['usdhkd_close'].iloc[0],4)

cu_fig.add_annotation(
    text=f"Date: {last_date.strftime('%Y-%m-%d')}<br>usdhkd: {last_usdhkd_close}",
    xref="paper", yref="paper",
    x=1, y=1.2, 
    showarrow=False,
    bgcolor="rgba(108, 1, 2, 1)",
    borderwidth=2,
    font=dict(size=12, color="white")
)

cu_fig.update_layout(
    xaxis_rangeslider_visible=True,
)

cu_fig.update_xaxes(
    rangeslider_visible=True,
    rangeselector=dict(
        buttons=list([
            dict(count=1, label="1m", step="month", stepmode="backward"),
            dict(count=6, label="6m", step="month", stepmode="backward"),
            dict(count=1, label="YTD", step="year", stepmode="todate"),
            dict(count=1, label="1y", step="year", stepmode="backward"),
            dict(step="all")
        ])
    )
)

cu_fig.show()

# 3.2 Trade-Weighted Index, TWI

In [14]:
hkdtwi_df = df[['end_of_date', 'twi']].head(251)

In [61]:
hkdtwi_fig = px.line(hkdtwi_df,
             x='end_of_date', y='twi',
             title='HKD Trade-Weighted Index (TWI)',
             labels={'end_of_date': 'Date', 'value': 'Value'},
             )


last_date = hkdtwi_df['end_of_date'].iloc[0]
last_twi = hkdtwi_df['twi'].iloc[0]

hkdtwi_fig.add_annotation(
    text=f"Date: {last_date.strftime('%Y-%m-%d')}<br>TWI(HKD): {last_twi}",
    xref="paper", yref="paper",
    x=1, y=1.2,
    showarrow=False,
    bgcolor="rgba(156, 33, 315, 1)",
    borderwidth=2,
    font=dict(size=12, color="white")
)

hkdtwi_fig.update_layout(
    xaxis_rangeslider_visible=True,
)

hkdtwi_fig.update_xaxes(
    rangeslider_visible=True,
    rangeselector=dict(
        buttons=list([
            dict(count=1, label="1m", step="month", stepmode="backward"),
            dict(count=6, label="6m", step="month", stepmode="backward"),
            dict(count=1, label="YTD", step="year", stepmode="todate"),
            dict(count=1, label="1y", step="year", stepmode="backward"),
            dict(step="all")
        ])
    )
)

hkdtwi_fig.show()

# 4.0 Stock Market

In [16]:
hsi = yf.Ticker("^HSI")
hsi_df = hsi.history(period ='251d').reset_index()
hsi_df.set_index('Date', inplace=True)
hsi_df.index = hsi_df.index.tz_localize(None)
hsi_df.sort_values(by='Date', ascending=False, inplace=True)
hsi_df['day_change'] = hsi_df['Close'] - hsi_df['Open']
hsi_df = hsi_df.reset_index()
hsi_df

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,day_change
0,2025-08-28,25030.539062,25093.650391,24808.779297,24998.820312,0,0.0,0.0,-31.718750
1,2025-08-27,25626.169922,25653.919922,25140.169922,25201.759766,3871200000,0.0,0.0,-424.410156
2,2025-08-26,25714.910156,25819.699219,25524.919922,25524.919922,3635400000,0.0,0.0,-189.990234
3,2025-08-25,25606.880859,25918.859375,25590.619141,25829.910156,4143300000,0.0,0.0,223.029297
4,2025-08-22,25205.039062,25349.080078,25140.080078,25339.140625,3359400000,0.0,0.0,134.101562
...,...,...,...,...,...,...,...,...,...
246,2024-08-27,17663.800781,17879.269531,17624.419922,17874.669922,2702700000,0.0,0.0,210.869141
247,2024-08-26,17709.269531,17826.050781,17709.269531,17798.730469,1970100000,0.0,0.0,89.460938
248,2024-08-23,17521.179688,17635.699219,17493.080078,17612.099609,2054100000,0.0,0.0,90.919922
249,2024-08-22,17497.630859,17652.800781,17389.939453,17641.000000,2945700000,0.0,0.0,143.369141
250,2024-08-21,17313.859375,17415.480469,17232.130859,17391.009766,2060200000,0.0,0.0,77.150391

In [62]:
hsi_fig = px.line(hsi_df,
             x='Date', y='Close',
             title='HSI',
             labels={'Date': 'Date', 'value': 'Value'},
             )


last_date = hsi_df['Date'].iloc[0]
last_hsi = round(hsi_df['Close'].iloc[0],2)

hsi_fig.add_annotation(
    text=f"Date: {last_date.strftime('%Y-%m-%d')}<br>Index(HKD): {last_hsi}",
    xref="paper", yref="paper",
    x=1, y=1.2, 
    showarrow=False,
    bgcolor="rgba(156, 33, 315, 1)",
    borderwidth=2,
    font=dict(size=12, color="white")
)

hsi_fig.update_layout(
    xaxis_rangeslider_visible=True,
)

hsi_fig.update_xaxes(
    rangeslider_visible=True,
    rangeselector=dict(
        buttons=list([
            dict(count=1, label="1m", step="month", stepmode="backward"),
            dict(count=6, label="6m", step="month", stepmode="backward"),
            dict(count=1, label="YTD", step="year", stepmode="todate"),
            dict(count=1, label="1y", step="year", stepmode="backward"),
            dict(step="all")
        ])
    )
)

hsi_fig.show()

# 5.0 SOFR 1M

https://markets.newyorkfed.org/read?productCode=50&eventCodes=525&startDt={startDate}&endDt={endDate}&fields=averageIndex30days&sort=postDt:1

In [52]:
endDate = pd.Timestamp.now(tz='Asia/Hong_Kong').strftime('%Y-%m-%d')
startDate =(pd.Timestamp.now(tz='Asia/Hong_Kong') - pd.Timedelta(days=365)).strftime('%Y-%m-%d')

In [53]:
sofr_url = f"https://markets.newyorkfed.org/read?productCode=50&eventCodes=525&startDt={startDate}&endDt={endDate}&fields=averageIndex30days&sort=postDt:1"
sofr_response = requests.get(sofr_url).json()

In [54]:
sofr_df = pd.DataFrame([
    {'postDt': i['postDt'], 'averageIndex30days': json.loads(i['data'])['averageIndex30days']}
    for i in sofr_response['data']
])
sofr_df['postDt'] = pd.to_datetime(sofr_df['postDt'])
sofr_df.columns = ['date', 'SOFR_1M']
sofr_df

          date  SOFR_1M
0   2024-08-29  5.34650
1   2024-08-30  5.34650
2   2024-09-03  5.34140
3   2024-09-04  5.34106
4   2024-09-05  5.34207
..         ...      ...
244 2025-08-22  4.34973
245 2025-08-25  4.35439
246 2025-08-26  4.35474
247 2025-08-27  4.35541
248 2025-08-28  4.35541

[249 rows x 2 columns]

In [55]:
hibor_df2 = hibor_df[['date', '1 Month']]
hibor_df2.columns = ['date', 'HIBOR_1M']
hibor_df2

          date  HIBOR_1M
0   2025-08-29   3.30649
1   2025-08-28   3.30649
2   2025-08-27   3.23310
3   2025-08-26   2.81464
4   2025-08-25   2.72720
..         ...       ...
240 2024-09-04   3.88857
241 2024-09-03   3.89929
242 2024-09-02   3.93905
243 2024-08-30   3.93095
244 2024-08-29   3.92661

[245 rows x 2 columns]

In [72]:
hibor_sofr_df = pd.concat([sofr_df.set_index('date'), hibor_df2.set_index('date')], axis=1).dropna().reset_index()
hibor_sofr_df['SOFR minus HIBOR'] = hibor_sofr_df['SOFR_1M'] - hibor_sofr_df['HIBOR_1M']
hibor_sofr_df

          date  SOFR_1M  HIBOR_1M  SOFR minus HIBOR
0   2024-08-29  5.34650   3.92661           1.41989
1   2024-08-30  5.34650   3.93095           1.41555
2   2024-09-03  5.34140   3.89929           1.44211
3   2024-09-04  5.34106   3.88857           1.45249
4   2024-09-05  5.34207   3.88607           1.45600
..         ...      ...       ...               ...
230 2025-08-22  4.34973   2.77060           1.57913
231 2025-08-25  4.35439   2.72720           1.62719
232 2025-08-26  4.35474   2.81464           1.54010
233 2025-08-27  4.35541   3.23310           1.12231
234 2025-08-28  4.35541   3.30649           1.04892

[235 rows x 4 columns]

In [73]:
hibor_sofr_fig = px.line(
    hibor_sofr_df,
    x='date',
    y=['SOFR_1M', 'HIBOR_1M'],
    title='SOFR 1M vs HIBOR 1M',
    labels={'value': 'Rate (%)', 'date': 'Date'}
)


hibor_sofr_fig.update_layout(xaxis_rangeslider_visible=True)

hibor_sofr_fig.update_xaxes(
    rangeslider_visible=True,
    rangeselector=dict(
        buttons=list([
            dict(count=1, label="1m", step="month", stepmode="backward"),
            dict(count=6, label="6m", step="month", stepmode="backward"),
            dict(count=1, label="YTD", step="year", stepmode="todate"),
            dict(count=1, label="1y", step="year", stepmode="backward"),
            dict(step="all")
        ])
    )
)

hibor_sofr_fig.show()

In [74]:
# import plotly.express as px

fig_diff = px.area(
    hibor_sofr_df,
    x='date',
    y='SOFR minus HIBOR',
    title='SOFR 1M minus HIBOR 1M',
    labels={'date': 'Date', 'SOFR minus HIBOR': 'SOFR 1M - HIBOR 1M (%)'}
)
fig_diff.update_layout(xaxis_rangeslider_visible=True)
fig_diff.update_xaxes(
    rangeslider_visible=True,
    rangeselector=dict(
        buttons=list([
            dict(count=1, label="1m", step="month", stepmode="backward"),
            dict(count=6, label="6m", step="month", stepmode="backward"),
            dict(count=1, label="YTD", step="year", stepmode="todate"),
            dict(count=1, label="1y", step="year", stepmode="backward"),
            dict(step="all")
        ])
    )
)
fig_diff.show()